import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="px-[40px] py-[20px] shadow-md">
          <Link href={"/"}>
          <button className='font-[600] text-[18px]'>Home</button>
          </Link>
        </nav>
        <div className="px-[100px]">
          {children}
        </div>
      </body>

    </html>
  )
}
